---
apis:
  camera_group: "http://10.0.153.141:8000/getCameraGroup"
  topics: "http://10.0.153.141:8000/gettopics"

kafka:
  - 172.31.26.109:9092
event_topic:
  - app_events
minio:
  endpoint: 10.0.153.141:9000
  secret_key: fz7x9AcpZqB7YY0VxgiQAYtC4RZVPSaumQycHPrP
  access_key: BIVeLI5sayqshgRWSm5H
  secure: False

mongodb:
  host: "172.31.26.109"
  port: 27017
  connect: False
  database: "history"
  collection: "incidents"
  backupcollection: "failed"
  reportscollection: "reports"

readConfig: False
config:
  customer:
    - 1
    - 2
    - 3
  zone:
    - 1
    - 2
    - 3
  subsite:
    - 1
    - 2
    - 3
  location:
    - 1
    - 2 
    - 3
  group:
    - 1
    - 2
    - 3