---
apis:
  camera_group: "http://172.16.0.204:8051/getCameraGroup"
  topics: "http://172.16.0.204:8051/gettopics"

kafka:
  - 172.16.0.175:9092
  - 172.16.0.171:9092
  - 172.16.0.174:9092

minio:
  endpoint: 172.16.0.178:9000
  secret_key: ktIanRWzFYLkxuKV52uHn8t2K9xhsczfS74RUKUX
  access_key: 6uYsllVhmjkWALUCR5uD
  secure: False

mongodb:
  host: "172.16.0.204"
  port: 27017
  connect: False
  database: "history"
  collection: "incidents"
  backupcollection: "failed"
  reportscollection: "reports"

readConfig: true
config:
  customer:
    - 1
    - 2
    - 3
  zone:
    - 1
    - 2
    - 3
  subsite:
    - 1
    - 2
    - 3
  location:
    - 1
    - 2 
    - 3
  group:
    - 1
    - 2
    - 3
