---
apis:
  camera_group: "http://127.0.0.1:8000/getCameraGroup"
  topics: "http://127.0.0.1:8000/gettopics"

kafka:
  - 172.16.0.175:9092
  - 172.16.0.171:9092
  - 172.16.0.174:9092

minio:
  endpoint: 172.16.0.170:9000
  secret_key: yMHbGFngNM5OnuWFj5lUDBJozEjryGAPBeF34WuG
  access_key: R8mQTw7uevt178G216KM
  secure: False

mongodb:
  host: "172.16.0.170"
  port: 27017
  connect: False
  database: "history"
  collection: "raw"

readConfig: true
config:
  customer:
    - 1
    - 2
    - 3
  zone:
    - 1
    - 2
    - 3
  subsite:
    - 1
    - 2
    - 3
  location:
    - 1
    - 2 
    - 3
  group:
    - 1
    - 2
    - 3
